// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package sqlcdb

import (
	"time"
)

type CuidadoresPacientes struct {
	ID         int64  `json:"id"`
	CuidadorID int64  `json:"cuidador_id"`
	PacienteID int64  `json:"paciente_id"`
	Relacion   string `json:"relacion"`
}

type Farmacias struct {
	ID        string  `json:"id"`
	Nombre    string  `json:"nombre"`
	Direccion string  `json:"direccion"`
	Telefono  string  `json:"telefono"`
	Latitud   float64 `json:"latitud"`
	Longitud  float64 `json:"longitud"`
}

type HistorialMedicaciones struct {
	ID           int64     `json:"id"`
	MedicacionID int64     `json:"medicacion_id"`
	FechaHora    time.Time `json:"fecha_hora"`
	Tomada       bool      `json:"tomada"`
	Observacion  string    `json:"observacion"`
}

type Medicaciones struct {
	ID                int64     `json:"id"`
	Nombre            string    `json:"nombre"`
	Descripcion       string    `json:"descripcion"`
	Dosis             string    `json:"dosis"`
	Frecuencia        string    `json:"frecuencia"`
	HoraProgramada    string    `json:"hora_programada"`
	InicioTratamiento time.Time `json:"inicio_tratamiento"`
	FechaCreacion     time.Time `json:"fecha_creacion"`
	PacienteID        int64     `json:"paciente_id"`
}

type Pacientes struct {
	ID     int64  `json:"id"`
	Nombre string `json:"nombre"`
	Edad   int64  `json:"edad"`
}
