// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: queries.sql

package sqlcdb

import (
	"context"
	"time"
)

const actualizarFarmacia = `-- name: ActualizarFarmacia :one
UPDATE farmacias
SET nombre = $1, direccion = $2, telefono = $3, latitud = $4, longitud = $5
WHERE id = $6
RETURNING id, nombre, direccion, telefono, latitud, longitud
`

type ActualizarFarmaciaParams struct {
	Nombre    string  `json:"nombre"`
	Direccion string  `json:"direccion"`
	Telefono  string  `json:"telefono"`
	Latitud   float32 `json:"latitud"`
	Longitud  float32 `json:"longitud"`
	ID        string  `json:"id"`
}

func (q *Queries) ActualizarFarmacia(ctx context.Context, arg ActualizarFarmaciaParams) (Farmacias, error) {
	row := q.db.QueryRowContext(ctx, actualizarFarmacia,
		arg.Nombre,
		arg.Direccion,
		arg.Telefono,
		arg.Latitud,
		arg.Longitud,
		arg.ID,
	)
	var i Farmacias
	err := row.Scan(
		&i.ID,
		&i.Nombre,
		&i.Direccion,
		&i.Telefono,
		&i.Latitud,
		&i.Longitud,
	)
	return i, err
}

const actualizarHistorial = `-- name: ActualizarHistorial :one
UPDATE historial_medicaciones
SET medicacion_id = $1, fecha_hora = $2, tomada = $3, observacion = $4
WHERE id = $5
RETURNING id, medicacion_id, fecha_hora, tomada, observacion
`

type ActualizarHistorialParams struct {
	MedicacionID int32     `json:"medicacion_id"`
	FechaHora    time.Time `json:"fecha_hora"`
	Tomada       bool      `json:"tomada"`
	Observacion  string    `json:"observacion"`
	ID           int32     `json:"id"`
}

func (q *Queries) ActualizarHistorial(ctx context.Context, arg ActualizarHistorialParams) (HistorialMedicaciones, error) {
	row := q.db.QueryRowContext(ctx, actualizarHistorial,
		arg.MedicacionID,
		arg.FechaHora,
		arg.Tomada,
		arg.Observacion,
		arg.ID,
	)
	var i HistorialMedicaciones
	err := row.Scan(
		&i.ID,
		&i.MedicacionID,
		&i.FechaHora,
		&i.Tomada,
		&i.Observacion,
	)
	return i, err
}

const actualizarMedicacion = `-- name: ActualizarMedicacion :one
UPDATE medicaciones
SET nombre = $1, descripcion = $2, dosis = $3, frecuencia = $4, hora_programada = $5,
    inicio_tratamiento = $6, fecha_creacion = $7, paciente_id = $8
WHERE id = $9
RETURNING id, nombre, descripcion, dosis, frecuencia, hora_programada, inicio_tratamiento, fecha_creacion, paciente_id
`

type ActualizarMedicacionParams struct {
	Nombre            string    `json:"nombre"`
	Descripcion       string    `json:"descripcion"`
	Dosis             string    `json:"dosis"`
	Frecuencia        string    `json:"frecuencia"`
	HoraProgramada    string    `json:"hora_programada"`
	InicioTratamiento time.Time `json:"inicio_tratamiento"`
	FechaCreacion     time.Time `json:"fecha_creacion"`
	PacienteID        int32     `json:"paciente_id"`
	ID                int32     `json:"id"`
}

func (q *Queries) ActualizarMedicacion(ctx context.Context, arg ActualizarMedicacionParams) (Medicaciones, error) {
	row := q.db.QueryRowContext(ctx, actualizarMedicacion,
		arg.Nombre,
		arg.Descripcion,
		arg.Dosis,
		arg.Frecuencia,
		arg.HoraProgramada,
		arg.InicioTratamiento,
		arg.FechaCreacion,
		arg.PacienteID,
		arg.ID,
	)
	var i Medicaciones
	err := row.Scan(
		&i.ID,
		&i.Nombre,
		&i.Descripcion,
		&i.Dosis,
		&i.Frecuencia,
		&i.HoraProgramada,
		&i.InicioTratamiento,
		&i.FechaCreacion,
		&i.PacienteID,
	)
	return i, err
}

const actualizarPaciente = `-- name: ActualizarPaciente :one
UPDATE pacientes
SET nombre = $1, edad = $2
WHERE id = $3
RETURNING id, nombre, edad
`

type ActualizarPacienteParams struct {
	Nombre string `json:"nombre"`
	Edad   int32  `json:"edad"`
	ID     int32  `json:"id"`
}

func (q *Queries) ActualizarPaciente(ctx context.Context, arg ActualizarPacienteParams) (Pacientes, error) {
	row := q.db.QueryRowContext(ctx, actualizarPaciente, arg.Nombre, arg.Edad, arg.ID)
	var i Pacientes
	err := row.Scan(&i.ID, &i.Nombre, &i.Edad)
	return i, err
}

const actualizarRelacion = `-- name: ActualizarRelacion :one
UPDATE cuidadores_pacientes
SET cuidador_id = $1, paciente_id = $2, relacion = $3
WHERE id = $4
RETURNING id, cuidador_id, paciente_id, relacion
`

type ActualizarRelacionParams struct {
	CuidadorID int32  `json:"cuidador_id"`
	PacienteID int32  `json:"paciente_id"`
	Relacion   string `json:"relacion"`
	ID         int32  `json:"id"`
}

func (q *Queries) ActualizarRelacion(ctx context.Context, arg ActualizarRelacionParams) (CuidadoresPacientes, error) {
	row := q.db.QueryRowContext(ctx, actualizarRelacion,
		arg.CuidadorID,
		arg.PacienteID,
		arg.Relacion,
		arg.ID,
	)
	var i CuidadoresPacientes
	err := row.Scan(
		&i.ID,
		&i.CuidadorID,
		&i.PacienteID,
		&i.Relacion,
	)
	return i, err
}

const crearFarmacia = `-- name: CrearFarmacia :one
INSERT INTO farmacias (id, nombre, direccion, telefono, latitud, longitud)
VALUES ($1, $2, $3, $4, $5, $6)
RETURNING id, nombre, direccion, telefono, latitud, longitud
`

type CrearFarmaciaParams struct {
	ID        string  `json:"id"`
	Nombre    string  `json:"nombre"`
	Direccion string  `json:"direccion"`
	Telefono  string  `json:"telefono"`
	Latitud   float32 `json:"latitud"`
	Longitud  float32 `json:"longitud"`
}

func (q *Queries) CrearFarmacia(ctx context.Context, arg CrearFarmaciaParams) (Farmacias, error) {
	row := q.db.QueryRowContext(ctx, crearFarmacia,
		arg.ID,
		arg.Nombre,
		arg.Direccion,
		arg.Telefono,
		arg.Latitud,
		arg.Longitud,
	)
	var i Farmacias
	err := row.Scan(
		&i.ID,
		&i.Nombre,
		&i.Direccion,
		&i.Telefono,
		&i.Latitud,
		&i.Longitud,
	)
	return i, err
}

const crearHistorial = `-- name: CrearHistorial :one
INSERT INTO historial_medicaciones (medicacion_id, fecha_hora, tomada, observacion)
VALUES ($1, $2, $3, $4)
RETURNING id, medicacion_id, fecha_hora, tomada, observacion
`

type CrearHistorialParams struct {
	MedicacionID int32     `json:"medicacion_id"`
	FechaHora    time.Time `json:"fecha_hora"`
	Tomada       bool      `json:"tomada"`
	Observacion  string    `json:"observacion"`
}

func (q *Queries) CrearHistorial(ctx context.Context, arg CrearHistorialParams) (HistorialMedicaciones, error) {
	row := q.db.QueryRowContext(ctx, crearHistorial,
		arg.MedicacionID,
		arg.FechaHora,
		arg.Tomada,
		arg.Observacion,
	)
	var i HistorialMedicaciones
	err := row.Scan(
		&i.ID,
		&i.MedicacionID,
		&i.FechaHora,
		&i.Tomada,
		&i.Observacion,
	)
	return i, err
}

const crearMedicacion = `-- name: CrearMedicacion :one
INSERT INTO medicaciones (
    nombre, descripcion, dosis, frecuencia, hora_programada,
    inicio_tratamiento, fecha_creacion, paciente_id
) VALUES ($1, $2, $3, $4, $5, $6, $7, $8)
RETURNING id, nombre, descripcion, dosis, frecuencia, hora_programada, inicio_tratamiento, fecha_creacion, paciente_id
`

type CrearMedicacionParams struct {
	Nombre            string    `json:"nombre"`
	Descripcion       string    `json:"descripcion"`
	Dosis             string    `json:"dosis"`
	Frecuencia        string    `json:"frecuencia"`
	HoraProgramada    string    `json:"hora_programada"`
	InicioTratamiento time.Time `json:"inicio_tratamiento"`
	FechaCreacion     time.Time `json:"fecha_creacion"`
	PacienteID        int32     `json:"paciente_id"`
}

func (q *Queries) CrearMedicacion(ctx context.Context, arg CrearMedicacionParams) (Medicaciones, error) {
	row := q.db.QueryRowContext(ctx, crearMedicacion,
		arg.Nombre,
		arg.Descripcion,
		arg.Dosis,
		arg.Frecuencia,
		arg.HoraProgramada,
		arg.InicioTratamiento,
		arg.FechaCreacion,
		arg.PacienteID,
	)
	var i Medicaciones
	err := row.Scan(
		&i.ID,
		&i.Nombre,
		&i.Descripcion,
		&i.Dosis,
		&i.Frecuencia,
		&i.HoraProgramada,
		&i.InicioTratamiento,
		&i.FechaCreacion,
		&i.PacienteID,
	)
	return i, err
}

const crearPaciente = `-- name: CrearPaciente :one
INSERT INTO pacientes (nombre, edad)
VALUES ($1, $2)
RETURNING id, nombre, edad
`

type CrearPacienteParams struct {
	Nombre string `json:"nombre"`
	Edad   int32  `json:"edad"`
}

func (q *Queries) CrearPaciente(ctx context.Context, arg CrearPacienteParams) (Pacientes, error) {
	row := q.db.QueryRowContext(ctx, crearPaciente, arg.Nombre, arg.Edad)
	var i Pacientes
	err := row.Scan(&i.ID, &i.Nombre, &i.Edad)
	return i, err
}

const crearRelacion = `-- name: CrearRelacion :one
INSERT INTO cuidadores_pacientes (cuidador_id, paciente_id, relacion)
VALUES ($1, $2, $3)
RETURNING id, cuidador_id, paciente_id, relacion
`

type CrearRelacionParams struct {
	CuidadorID int32  `json:"cuidador_id"`
	PacienteID int32  `json:"paciente_id"`
	Relacion   string `json:"relacion"`
}

func (q *Queries) CrearRelacion(ctx context.Context, arg CrearRelacionParams) (CuidadoresPacientes, error) {
	row := q.db.QueryRowContext(ctx, crearRelacion, arg.CuidadorID, arg.PacienteID, arg.Relacion)
	var i CuidadoresPacientes
	err := row.Scan(
		&i.ID,
		&i.CuidadorID,
		&i.PacienteID,
		&i.Relacion,
	)
	return i, err
}

const eliminarFarmacia = `-- name: EliminarFarmacia :exec
DELETE FROM farmacias WHERE id = $1
`

func (q *Queries) EliminarFarmacia(ctx context.Context, id string) error {
	_, err := q.db.ExecContext(ctx, eliminarFarmacia, id)
	return err
}

const eliminarHistorial = `-- name: EliminarHistorial :exec
DELETE FROM historial_medicaciones WHERE id = $1
`

func (q *Queries) EliminarHistorial(ctx context.Context, id int32) error {
	_, err := q.db.ExecContext(ctx, eliminarHistorial, id)
	return err
}

const eliminarMedicacion = `-- name: EliminarMedicacion :exec
DELETE FROM medicaciones WHERE id = $1
`

func (q *Queries) EliminarMedicacion(ctx context.Context, id int32) error {
	_, err := q.db.ExecContext(ctx, eliminarMedicacion, id)
	return err
}

const eliminarPaciente = `-- name: EliminarPaciente :exec
DELETE FROM pacientes WHERE id = $1
`

func (q *Queries) EliminarPaciente(ctx context.Context, id int32) error {
	_, err := q.db.ExecContext(ctx, eliminarPaciente, id)
	return err
}

const eliminarRelacion = `-- name: EliminarRelacion :exec
DELETE FROM cuidadores_pacientes WHERE id = $1
`

func (q *Queries) EliminarRelacion(ctx context.Context, id int32) error {
	_, err := q.db.ExecContext(ctx, eliminarRelacion, id)
	return err
}

const listarFarmacias = `-- name: ListarFarmacias :many
SELECT id, nombre, direccion, telefono, latitud, longitud FROM farmacias
`

// Farmacias
func (q *Queries) ListarFarmacias(ctx context.Context) ([]Farmacias, error) {
	rows, err := q.db.QueryContext(ctx, listarFarmacias)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Farmacias
	for rows.Next() {
		var i Farmacias
		if err := rows.Scan(
			&i.ID,
			&i.Nombre,
			&i.Direccion,
			&i.Telefono,
			&i.Latitud,
			&i.Longitud,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listarHistorial = `-- name: ListarHistorial :many
SELECT id, medicacion_id, fecha_hora, tomada, observacion FROM historial_medicaciones
`

// Historial de Medicaciones
func (q *Queries) ListarHistorial(ctx context.Context) ([]HistorialMedicaciones, error) {
	rows, err := q.db.QueryContext(ctx, listarHistorial)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []HistorialMedicaciones
	for rows.Next() {
		var i HistorialMedicaciones
		if err := rows.Scan(
			&i.ID,
			&i.MedicacionID,
			&i.FechaHora,
			&i.Tomada,
			&i.Observacion,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listarHistorialPorPaciente = `-- name: ListarHistorialPorPaciente :many
SELECT h.id, h.medicacion_id, h.fecha_hora, h.tomada, h.observacion
FROM historial_medicaciones h
JOIN medicaciones m ON h.medicacion_id = m.id
WHERE m.paciente_id = $1
`

func (q *Queries) ListarHistorialPorPaciente(ctx context.Context, pacienteID int32) ([]HistorialMedicaciones, error) {
	rows, err := q.db.QueryContext(ctx, listarHistorialPorPaciente, pacienteID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []HistorialMedicaciones
	for rows.Next() {
		var i HistorialMedicaciones
		if err := rows.Scan(
			&i.ID,
			&i.MedicacionID,
			&i.FechaHora,
			&i.Tomada,
			&i.Observacion,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listarMedicaciones = `-- name: ListarMedicaciones :many
SELECT id, nombre, descripcion, dosis, frecuencia, hora_programada, inicio_tratamiento, fecha_creacion, paciente_id FROM medicaciones
`

// Medicaciones
func (q *Queries) ListarMedicaciones(ctx context.Context) ([]Medicaciones, error) {
	rows, err := q.db.QueryContext(ctx, listarMedicaciones)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Medicaciones
	for rows.Next() {
		var i Medicaciones
		if err := rows.Scan(
			&i.ID,
			&i.Nombre,
			&i.Descripcion,
			&i.Dosis,
			&i.Frecuencia,
			&i.HoraProgramada,
			&i.InicioTratamiento,
			&i.FechaCreacion,
			&i.PacienteID,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listarMedicacionesPorPaciente = `-- name: ListarMedicacionesPorPaciente :many
SELECT id, nombre, descripcion, dosis, frecuencia, hora_programada, inicio_tratamiento, fecha_creacion, paciente_id FROM medicaciones WHERE paciente_id = $1
`

func (q *Queries) ListarMedicacionesPorPaciente(ctx context.Context, pacienteID int32) ([]Medicaciones, error) {
	rows, err := q.db.QueryContext(ctx, listarMedicacionesPorPaciente, pacienteID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Medicaciones
	for rows.Next() {
		var i Medicaciones
		if err := rows.Scan(
			&i.ID,
			&i.Nombre,
			&i.Descripcion,
			&i.Dosis,
			&i.Frecuencia,
			&i.HoraProgramada,
			&i.InicioTratamiento,
			&i.FechaCreacion,
			&i.PacienteID,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listarPacientes = `-- name: ListarPacientes :many
SELECT id, nombre, edad FROM pacientes
`

// Pacientes
func (q *Queries) ListarPacientes(ctx context.Context) ([]Pacientes, error) {
	rows, err := q.db.QueryContext(ctx, listarPacientes)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Pacientes
	for rows.Next() {
		var i Pacientes
		if err := rows.Scan(&i.ID, &i.Nombre, &i.Edad); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listarRelaciones = `-- name: ListarRelaciones :many
SELECT id, cuidador_id, paciente_id, relacion FROM cuidadores_pacientes
`

// Monitoreo (cuidadores_pacientes)
func (q *Queries) ListarRelaciones(ctx context.Context) ([]CuidadoresPacientes, error) {
	rows, err := q.db.QueryContext(ctx, listarRelaciones)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []CuidadoresPacientes
	for rows.Next() {
		var i CuidadoresPacientes
		if err := rows.Scan(
			&i.ID,
			&i.CuidadorID,
			&i.PacienteID,
			&i.Relacion,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const obtenerFarmaciaPorID = `-- name: ObtenerFarmaciaPorID :one
SELECT id, nombre, direccion, telefono, latitud, longitud FROM farmacias WHERE id = $1
`

func (q *Queries) ObtenerFarmaciaPorID(ctx context.Context, id string) (Farmacias, error) {
	row := q.db.QueryRowContext(ctx, obtenerFarmaciaPorID, id)
	var i Farmacias
	err := row.Scan(
		&i.ID,
		&i.Nombre,
		&i.Direccion,
		&i.Telefono,
		&i.Latitud,
		&i.Longitud,
	)
	return i, err
}

const obtenerHistorialPorID = `-- name: ObtenerHistorialPorID :one
SELECT id, medicacion_id, fecha_hora, tomada, observacion FROM historial_medicaciones WHERE id = $1
`

func (q *Queries) ObtenerHistorialPorID(ctx context.Context, id int32) (HistorialMedicaciones, error) {
	row := q.db.QueryRowContext(ctx, obtenerHistorialPorID, id)
	var i HistorialMedicaciones
	err := row.Scan(
		&i.ID,
		&i.MedicacionID,
		&i.FechaHora,
		&i.Tomada,
		&i.Observacion,
	)
	return i, err
}

const obtenerMedicacionPorID = `-- name: ObtenerMedicacionPorID :one
SELECT id, nombre, descripcion, dosis, frecuencia, hora_programada, inicio_tratamiento, fecha_creacion, paciente_id FROM medicaciones WHERE id = $1
`

func (q *Queries) ObtenerMedicacionPorID(ctx context.Context, id int32) (Medicaciones, error) {
	row := q.db.QueryRowContext(ctx, obtenerMedicacionPorID, id)
	var i Medicaciones
	err := row.Scan(
		&i.ID,
		&i.Nombre,
		&i.Descripcion,
		&i.Dosis,
		&i.Frecuencia,
		&i.HoraProgramada,
		&i.InicioTratamiento,
		&i.FechaCreacion,
		&i.PacienteID,
	)
	return i, err
}

const obtenerPacientePorID = `-- name: ObtenerPacientePorID :one
SELECT id, nombre, edad FROM pacientes WHERE id = $1
`

func (q *Queries) ObtenerPacientePorID(ctx context.Context, id int32) (Pacientes, error) {
	row := q.db.QueryRowContext(ctx, obtenerPacientePorID, id)
	var i Pacientes
	err := row.Scan(&i.ID, &i.Nombre, &i.Edad)
	return i, err
}

const obtenerRelacionPorID = `-- name: ObtenerRelacionPorID :one
SELECT id, cuidador_id, paciente_id, relacion FROM cuidadores_pacientes WHERE id = $1
`

func (q *Queries) ObtenerRelacionPorID(ctx context.Context, id int32) (CuidadoresPacientes, error) {
	row := q.db.QueryRowContext(ctx, obtenerRelacionPorID, id)
	var i CuidadoresPacientes
	err := row.Scan(
		&i.ID,
		&i.CuidadorID,
		&i.PacienteID,
		&i.Relacion,
	)
	return i, err
}
