name: Go CI

on:
  push:
    branches:
      - main
      - master
      - develop
      - feature/**
  pull_request:
    branches:
      - main
      - master

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Clonar repositorio
        uses: actions/checkout@v4

      - name: Instalar Go
        uses: actions/setup-go@v5
        with:
          go-version: "1.24"

      - name: Descargar dependencias
        run: go mod tidy

      - name: Compilar proyecto
        run: go build ./...

      - name: Ejecutar Go Vet
        run: go vet ./...

      - name: Ejecutar Tests
        run: go test ./... -v